services:
  devcontainer:
    container_name: frigate-devcontainer
    # Check host system's actual render/video/plugdev group IDs with 'getent group render', 'getent group video', and 'getent group plugdev'
    # Must add these exact IDs in container's group_add section or OpenVINO GPU acceleration will fail
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "256mb"
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      # Use target devcontainer-trt for TensorRT dev
      target: devcontainer
    ## Uncomment this block for nvidia gpu support
    # deploy:
    #       resources:
    #           reservations:
    #               devices:
    #                   - driver: nvidia
    #                     count: 1
    #                     capabilities: [gpu]
    environment:
      YOLO_MODELS: ""
    devices:
      - /dev/dri/renderD129:/dev/dri/renderD129
      - /dev/dri/card1:/dev/dri/card1
    volumes:
      - .:/workspace/frigate:cached
      - ./web/dist:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/frigate
     # - /dev/bus/usb:/dev/bus/usb # Uncomment for Google Coral USB
    ports:
      - "21984:1984" #rtsp web interface
      - "28971:8971"
      - "25000:5000"
      - "28554:8554" # RTSP feeds
      - "28555:8555/tcp" # WebRTC over tcp
      - "28555:8555/udp" # WebRTC over udp
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0
    command: mosquitto -c /mosquitto-no-auth.conf # enable no-auth mode
    ports:
      - "1883:1883"
